spring.application.name=ecommerce

# Database
#spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
#spring.datasource.username=root
#spring.datasource.password=root
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql-35e022a3-ganesh-7c1e.g.aivencloud.com:26861/defaultdb?ssl-mode=REQUIRED}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:avnadmin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081

# JWT secret (used in JwtService)
jwt.secret=myverysecuresecretkeymyverysecuresecretkey12345